[tool.poetry]
name = "thetagang-notifications"
version = "1.2.1"
description = "Notifications for the Theta Gang discord."
authors = ["Major Hayden <major@mhtx.net>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.10"
discord-webhook = "^1.0.0"
python-dateutil = "^2.8.2"
requests = "^2.28.2"
tld = "^0.12.6"
PyYAML = "^6.0"
finviz = "^1.4.5"
schedule = "^1.1.0"
inflect = "^6.0.2"
sentry-sdk = "^1.14.0"

[tool.poetry.group.dev.dependencies]
freezegun = "^1.2.2"
pytest = "^7.2.1"
pytest-clarity = "^1.0.1"
pytest-mock = "^3.10.0"
pytest-randomly = "^3.12.0"
requests-mock = "^1.10.0"
ipython = "^8.9.0"
pre-commit = "^3.0.3"
pylint = "^2.16.0"
mypy = "^0.991"
bandit = "^1.7.4"
black = {extras = ["d"], version = "^23.1.0"}
types-requests = "^2.28.11.8"
pytest-recording = "^0.12.1"
flake8 = "^6.0.0"
pytest-xdist = "^3.1.0"
coverage = "^7.1.0"
pytest-cov = "^4.0.0"
pytest-sugar = "^0.9.6"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-n auto --block-network --cov-report term-missing --cov-branch --cov-report html --cov=thetagang_notifications --cov-fail-under=100"
testpaths = [
    "tests"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
