[tool.poetry]
name = "thetagang-notifications"
version = "1.2.1"
description = "Notifications for the Theta Gang discord."
authors = ["Major Hayden <major@mhtx.net>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.10"
discord-webhook = "^1.3.0"
python-dateutil = "^2.8.2"
requests = "^2.31.0"
PyYAML = "^6.0.1"
schedule = "^1.2.1"
inflect = "^7.0.0"
sentry-sdk = "^1.39.2"
redis = "^5.0.1"

[tool.poetry.group.dev.dependencies]
freezegun = "^1.4.0"
pytest = "^8.0.0"
pytest-clarity = "^1.0.1"
pytest-mock = "^3.12.0"
pytest-randomly = "^3.15.0"
requests-mock = "^1.11.0"
ipython = "^8.20.0"
types-requests = "^2.31.0.20240106"
pytest-cov = "^4.1.0"
pytest-sugar = "^0.9.7"
deptry = "^0.12.0"
mypy = "^1.8.0"
ruff = "^0.1.0"
pre-commit = "^3.6.0"
tox = "^4.12.1"
pytest-recording = "^0.13.0"
vcrpy = "^6.0.0"
fakeredis = "^2.20.1"
types-redis = "^4.6.0.20240106"
pytest-xdist = "^3.5.0"
responses = "^0.24.0"
coverage = {extras = ["toml"], version = "^7.4.0"}

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest]
addopts = "-n auto --cov --cov-config=pyproject.toml --cov-report xml:cov.xml --cov-report=html --cov-report=term-missing -p no:warnings --record-mode=once"
minversion = "7.4"

[tool.black]
line-length = 120
target-version = ['py311']
preview = true

[tool.mypy]
files = ["thetagang_notifications"]
disallow_untyped_defs = "True"
disallow_any_unimported = "True"
no_implicit_optional = "True"
check_untyped_defs = "True"
warn_return_any = "True"
warn_unused_ignores = "True"
show_error_codes = "True"
ignore_missing_imports = "True"

[tool.ruff]
target-version = "py311"
line-length = 120
fix = true
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # LineTooLong
    "E501",
    # DoNotAssignLambda
    "E731",
]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["thetagang_notifications"]