[tool.poetry]
name = "thetagang-notifications"
version = "1.2.1"
description = "Notifications for the Theta Gang discord."
authors = ["Major Hayden <major@mhtx.net>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.10"
discord-webhook = "^1.0.0"
python-dateutil = "^2.8.2"
requests = "^2.28.2"
tld = "^0.12.6"
PyYAML = "^6.0"
finviz = "^1.4.5"

[tool.poetry.group.dev.dependencies]
freezegun = "^1.2.2"
pytest = "^7.2.1"
pytest-clarity = "^1.0.1"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
pytest-randomly = "^3.12.0"
requests-mock = "^1.10.0"
ipython = "^8.8.0"
pre-commit = "^2.21.0"
pylint = "^2.15.10"
mypy = "^0.991"
bandit = "^1.7.4"
black = {extras = ["d"], version = "^22.12.0"}
types-requests = "^2.28.11.8"
pytest-recording = "^0.12.1"
flake8 = "^6.0.0"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--ignore=setup.py --cov-report term-missing --cov-report html --cov-report xml:cov.xml --cov-branch --cov=thetagang_notifications"
testpaths = [
    "tests"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
