#!/usr/bin/env python
"""Set the schedule for running various notification tasks."""
import logging

from thetagang_notifications import trends


# Setup our shared logger.
log = logging.getLogger(__name__)
log.info("🚀 Running thetagang trades bot")


if __name__ == "__main__":  # pragma: no cover
    trends.main()
