#!/usr/bin/env python
"""Run the earnings bot."""
import logging

from thetagang_notifications import earnings

# Setup our shared logger.
log = logging.getLogger(__name__)
log.info("🚀 thetagang-notifications starting up!")


if __name__ == "__main__":
    # Start earnings notifications via Tweepy's stream thread.
    earnings.main()
