#!/usr/bin/env python
"""Run the trades bot."""
import logging

from thetagang_notifications import trades

# Setup our shared logger.
log = logging.getLogger(__name__)
log.info("🚀 Running thetagang trades bot")


if __name__ == "__main__":
    trades.main()
