#!/usr/bin/env python
"""Run the trends bot."""
import logging

from thetagang_notifications import trends

# Setup our shared logger.
log = logging.getLogger(__name__)
log.info("🚀 Running thetagang trends bot")


if __name__ == "__main__":
    trends.main()
