#!/usr/bin/env python
"""Run the trade bot."""
import logging

from thetagang_notifications.trade import get_handler
from thetagang_notifications.trade_queue import build_queue

# Setup our shared logger.
log = logging.getLogger(__name__)
log.info("🚀 Running thetagang trades bot")


def run_queue():
    """Enqueue the trades which need notifications."""
    for queued_trade in build_queue():
        trade_obj = get_handler(queued_trade)
        trade_obj.notify()


if __name__ == "__main__":
    run_queue()
